[MON-248] feat : 시리즈 ServiceLayer 테스트 구현
prgrms-web-devcourse/Team_Sagack_MonthSub_BE pull request #153
Opened 2022-01-07 04:52 UTC by YOUJI2

## 🦓 지라 link
https://monthsub.atlassian.net/browse/MON-248?atlOrigin=eyJpIjoiYzFmZjRkOWM1NGJlNDkxNGJkZjliNzg4YjIyYTViY2YiLCJwIjoiaiJ9

## 👩‍💻 AS-IS

- [x] :  시리즈 단위 테스트 구현

2022-01-07 05:00 UTC, eunseo2 commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    doReturn(series).when(seriesRepository).save(any());
this.seriesRepository

2022-01-07 05:41 UTC, 0923kdh approved these changes
엔티티 mocking 부분 수정 부탁드립니다~

2022-01-08 12:44 UTC, eunseo2 commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    }
반복문 대신 findRecentSortList와 recentSeriesList가 같은지 비교하는 방법은 어떤가요?0?

2022-01-08 12:45 UTC, eunseo2 commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    }
assertThat(recentSeriesList, is(findRecentSortList));

2022-01-09 16:09 UTC, YOUJI2 commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    }
그것도 좋은방법이군요! 감사합니다

2022-01-13 13:50 UTC, 0923kdh requested changes

2022-01-13 13:50 UTC, 0923kdh commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +      SeriesStatus.SUBSCRIPTION_AVAILABLE, pageable);
List<Series> findSeries = this.seriesService.findBySubscribeStatus(
      SeriesStatus.SUBSCRIPTION_AVAILABLE, pageable
);

2022-01-13 13:50 UTC, 0923kdh commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +      PAGE_NUM, SERIES_SIZE, Sort.by(Direction.DESC, "createdAt", "id"));
Pageable pageable = PageRequest.of(
      PAGE_NUM, SERIES_SIZE, Sort.by(Direction.DESC, "createdAt", "id")
);

2022-01-13 13:50 UTC, 0923kdh commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    when(articleUploadDateRepository.save(any(ArticleUploadDate.class))).thenReturn(
when(articleUploadDateRepository.save(any(ArticleUploadDate.class)))
.thenReturn(articleUploadDate);

2022-01-13 13:50 UTC, 0923kdh commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    ReflectionTestUtils.setField(series, "createdAt", LocalDateTime.now());
개행 한줄 넣고 return 해주세요~

2022-01-13 13:50 UTC, 0923kdh commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    ReflectionTestUtils.setField(writer, "id", id);
개행 한줄 넣고 return 해주세요~

2022-01-13 13:50 UTC, 0923kdh commented on src/test/java/com/prgrms/monthsub/module/series/series/app/SeriesServiceTest.java
> +    ReflectionTestUtils.setField(articleUploadDate, "id", id);
개행 한줄 넣고 return 해주세요~

2022-01-16 17:43 UTC, merged